# Generated by Django 5.1.4 on 2025-01-11 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='書籍名')),
                ('isbn', models.CharField(max_length=13, verbose_name='ISBN')),
                ('content', models.TextField(blank=True, verbose_name='書籍概要')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='表紙画像')),
                ('refer', models.TextField(blank=True, null=True, verbose_name='引用')),
                ('refer_url', models.URLField(blank=True, null=True, verbose_name='参考URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': '書籍',
            },
        ),
    ]
