# Generated by Django 5.1.4 on 2025-01-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='photo',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='book',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='書籍概要'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='ISBN'),
        ),
    ]
